apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: emarionpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emarionpipelinesjavascriptdocker 
    spec:
      containers:
        - name: emarionpipelinesjavascriptdocker 
          image: rcontainer2.azurecr.io/emarionpipelinesjavascriptdocker
          ports:
          - containerPort: 8080